import Alarm from './models/Alarm';
declare function scheduleAlarm(alarm: Alarm): Promise<void>;
declare function enableAlarm(uid: number): Promise<void>;
declare function disableAlarm(uid: number): Promise<void>;
declare function stopAlarm(): Promise<void>;
declare function snoozeAlarm(): Promise<void>;
declare function removeAlarm(uid: number): Promise<void>;
declare function updateAlarm(alarm: Alarm): Promise<void>;
declare function removeAllAlarms(): Promise<void>;
declare function getAllAlarms(): Promise<any>;
declare function getAlarm(uid: number): Promise<Alarm>;
declare function getAlarmState(): Promise<any>;
export default Alarm;
export { scheduleAlarm, enableAlarm, disableAlarm, stopAlarm, snoozeAlarm, removeAlarm, updateAlarm, removeAllAlarms, getAllAlarms, getAlarm, getAlarmState };
